# Generated by Django 5.1.15 on 2026-06-18 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0061_task_project_file_upload_idx_async"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "In progress"),
                    ("COMPLETED", "Completed"),
                    ("REWORK_REQUIRED", "Rework required"),
                    ("APPROVED", "Approved"),
                ],
                db_index=True,
                default="COMPLETED",
                help_text="Annotation revision status used by the review workflow. A submitted annotation is COMPLETED; review sets APPROVED or REWORK_REQUIRED.",
                max_length=32,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Revision number of this annotation within its task (1-based).",
                verbose_name="version",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="current_annotation",
            field=models.ForeignKey(
                blank=True,
                help_text="Latest active annotation revision for this task.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="tasks.annotation",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("NOT_SELECTED", "Not selected for review"),
                    ("PENDING", "Pending review"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("FIXED_AND_ACCEPTED", "Fixed and accepted"),
                ],
                db_index=True,
                default="NOT_SELECTED",
                help_text="Review state of the task current annotation (set by the review workflow).",
                max_length=32,
                verbose_name="review status",
            ),
        ),
    ]
