# Generated by Django 5.1.15 on 2026-04-23 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0037_projectmember_role_and_soft_delete"),
        ("tasks", "0061_task_project_file_upload_idx_async"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="current_state",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Denormalized latest FSM state. Mirrors the most recent AnnotationState record so lists/aggregates can filter without joining the history table.",
                max_length=32,
                null=True,
                verbose_name="current state",
            ),
        ),
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(
                fields=["current_state"], name="task_comple_current_4882ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(
                fields=["project", "current_state"],
                name="task_comple_project_1d1246_idx",
            ),
        ),
    ]
