# Generated by Django 5.1.15 on 2026-04-23 13:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0063_backfill_annotation_current_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewerLock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expire_at", models.DateTimeField(verbose_name="expire_at")),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "annotation",
                    models.ForeignKey(
                        help_text="Annotation held for review",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewer_locks",
                        to="tasks.annotation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Reviewer who holds this lock",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewer_locks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["annotation", "expire_at"],
                        name="tasks_revie_annotat_cdbe1a_idx",
                    ),
                    models.Index(
                        fields=["user", "expire_at"],
                        name="tasks_revie_user_id_740282_idx",
                    ),
                ],
            },
        ),
    ]
