# Generated by Django 5.1.15 on 2026-06-18 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0038_project_review_ratio_project_review_strategy"),
        ("tasks", "0062_annotation_status_annotation_version_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("ACCEPT", "Accept"),
                            ("REJECT", "Reject"),
                            ("FIX_AND_ACCEPT", "Fix and accept"),
                        ],
                        max_length=32,
                        verbose_name="decision",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, default="", verbose_name="comment"),
                ),
                (
                    "stage",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Review stage (1=first review). Reserved for multi-stage review workflows.",
                        verbose_name="stage",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "annotation",
                    models.ForeignKey(
                        help_text="Annotation revision being reviewed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="tasks.annotation",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project the reviewed annotation belongs to (denormalized for queries).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="projects.project",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the review.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "review",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "-created_at"],
                        name="review_project_bb545c_idx",
                    ),
                    models.Index(
                        fields=["annotation", "stage"], name="review_annotat_e24994_idx"
                    ),
                ],
            },
        ),
    ]
