# Generated by Django 5.1.15 on 2026-07-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="decision",
            field=models.CharField(
                choices=[
                    ("ACCEPT", "Accept"),
                    ("REJECT", "Reject"),
                    ("FIX_AND_ACCEPT", "Fix and accept"),
                    ("RESUBMITTED", "Resubmitted after edit"),
                ],
                max_length=32,
                verbose_name="decision",
            ),
        ),
    ]
