# Generated by Django 5.1.15 on 2026-04-23 14:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0039_project_review_instruction_project_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectPricing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label_price",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Unit price paid to the annotator for each accepted annotation.",
                        max_digits=14,
                        verbose_name="label price",
                    ),
                ),
                (
                    "review_price",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Unit price paid to the reviewer for each completed review (accept or reject).",
                        max_digits=14,
                        verbose_name="review price",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("KRW", "Korean Won"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("JPY", "Japanese Yen"),
                        ],
                        default="KRW",
                        max_length=8,
                        verbose_name="currency",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "project_pricing",
            },
        ),
        migrations.CreateModel(
            name="SettlementBatch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "label_price_snapshot",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "review_price_snapshot",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("KRW", "Korean Won"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("JPY", "Japanese Yen"),
                        ],
                        default="KRW",
                        max_length=8,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("accepted_annotation_count", models.PositiveIntegerField(default=0)),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement_batches",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "settlement_batch",
            },
        ),
        migrations.CreateModel(
            name="SettlementItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accepted_count", models.PositiveIntegerField(default=0)),
                ("review_count", models.PositiveIntegerField(default=0)),
                (
                    "label_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "review_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("KRW", "Korean Won"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("JPY", "Japanese Yen"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="settlement.settlementbatch",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "settlement_item",
            },
        ),
        migrations.CreateModel(
            name="ProjectPricingHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label_price", models.DecimalField(decimal_places=4, max_digits=14)),
                ("review_price", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("KRW", "Korean Won"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("JPY", "Japanese Yen"),
                        ],
                        max_length=8,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_history",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_pricing_history",
                "indexes": [
                    models.Index(
                        fields=["project", "-changed_at"],
                        name="project_pri_project_934f09_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="settlementbatch",
            index=models.Index(
                fields=["project", "-created_at"], name="settlement__project_f515f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="settlementbatch",
            index=models.Index(
                fields=["project", "status"], name="settlement__project_e93a62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="settlementitem",
            index=models.Index(
                fields=["batch", "-amount"], name="settlement__batch_i_5de6e0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="settlementitem",
            constraint=models.UniqueConstraint(
                fields=("batch", "user"), name="uniq_settlement_item_batch_user"
            ),
        ),
    ]
