# Generated by Django 5.1.15 on 2026-04-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsm", "0003_alter_annotationstate_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationstate",
            name="state",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("UPLOADED", "Uploaded"),
                    ("ASSIGNED", "Assigned"),
                    ("ANNOTATED", "Annotated"),
                    ("WILL_REVIEWED", "Will be reviewed"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="projectstate",
            name="state",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("IN_PROGRESS", "In Progress"),
                    ("CAN_REVIEWED", "Can be reviewed"),
                    ("COMPLETED", "Completed"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="taskstate",
            name="state",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
