# Generated by Django 5.1.15 on 2026-04-23 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0006_alter_organizationmember_deleted_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("role.granted", "Role granted"),
                            ("role.revoked", "Role revoked"),
                            ("role.changed", "Role changed"),
                            ("project.created", "Project created"),
                            ("project.updated", "Project updated"),
                            ("project.deleted", "Project deleted"),
                            ("workspace.created", "Workspace created"),
                            ("workspace.updated", "Workspace updated"),
                            ("workspace.deleted", "Workspace deleted"),
                            ("data.exported", "Data exported"),
                        ],
                        db_index=True,
                        help_text="Dotted event name (e.g. role.granted).",
                        max_length=64,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Target model label (e.g. 'projects.project'). Free-form string, not an FK.",
                        max_length=64,
                    ),
                ),
                (
                    "target_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Primary key of the target row.",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Event-specific payload (before/after diff, role name, export format, etc.).",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action. NULL for system actors.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization the action occurred within.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "audit_log",
                "indexes": [
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="audit_log_organiz_27eb85_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="audit_log_action_7c9e02_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="audit_log_target__0238a6_idx",
                    ),
                ],
            },
        ),
    ]
