# Generated by Django 5.1.15 on 2026-06-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0036_backfill_project_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="due_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Target completion date for the project (used by the workspace dashboard)",
                null=True,
                verbose_name="due date",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Free-form labels for filtering projects in the workspace dashboard",
                verbose_name="tags",
            ),
        ),
    ]
