# Generated by Django 5.1.15 on 2026-04-23 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0036_backfill_project_workspace"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmember",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=None,
                help_text="Timestamp indicating when the project member was soft-deleted. NULL means active.",
                null=True,
                verbose_name="deleted at",
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who removed this membership",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_memberships_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("project_manager", "Project Manager"),
                    ("annotator", "Annotator"),
                    ("reviewer", "Reviewer"),
                ],
                db_index=True,
                default="annotator",
                help_text="Project-scope role: project_manager, annotator, or reviewer.",
                max_length=32,
                verbose_name="role",
            ),
        ),
        migrations.AddIndex(
            model_name="projectmember",
            index=models.Index(
                fields=["project", "role"], name="projects_pr_project_5b8833_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("user", "project"),
                name="uniq_active_project_member",
            ),
        ),
    ]
