# Generated by Django 5.1.15 on 2026-06-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0037_project_due_date_project_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="review_ratio",
            field=models.FloatField(
                default=0.0,
                help_text="Fraction (0..1) of completed annotations sampled for review. Used only when review_strategy is RANDOM_SAMPLING.",
                verbose_name="review ratio",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="review_strategy",
            field=models.CharField(
                choices=[
                    ("NONE", "No review"),
                    ("RANDOM_SAMPLING", "Random sampling"),
                    ("FULL_REVIEW", "Full review"),
                    ("CUSTOM_RULE", "Custom rule"),
                ],
                default="NONE",
                help_text="How completed annotations are selected for review. Review runs as a workflow inside the project, not as a separate review project.",
                max_length=32,
                verbose_name="review strategy",
            ),
        ),
    ]
