# Generated by Django 5.1.15 on 2026-04-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0037_projectmember_role_and_soft_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="review_batch_size",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="Batch review threshold — when `fflag_batch_review` is enabled and this value is set, reviewers can start once this many annotations are in ANNOTATED state, instead of waiting for every task to be labeled.",
                null=True,
                verbose_name="review batch size",
            ),
        ),
    ]
