# Generated by Django 5.1.15 on 2026-06-18 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0038_project_review_ratio_project_review_strategy"),
        ("workspaces", "0004_datasetitem_workpool_workpoolitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="work_pool",
            field=models.ForeignKey(
                blank=True,
                help_text="Task pool whose items seed this project tasks (selected at creation).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="workspaces.workpool",
            ),
        ),
    ]
