# Generated by Django 5.1.15 on 2026-04-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0038_project_review_batch_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="review_instruction",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Plain-text review criteria shown to reviewers (§3.4.1). Separate from `expert_instruction` (HTML labeling guide) so reviewers see a dedicated rubric when judging accept / reject.",
                null=True,
                verbose_name="review instruction",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[("annotation", "Annotation"), ("review", "Review")],
                default="annotation",
                help_text='Project mode — "annotation" for standard labeling projects, "review" for projects dedicated to reviewing annotations from an upstream project.',
                max_length=16,
                verbose_name="project type",
            ),
        ),
    ]
