# Generated by Django 5.1.15 on 2026-06-30 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0040_rename_work_pool_to_task_pool"),
        ("workspaces", "0006_remove_taskpoolitem_uniq_work_pool_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="task_pool",
            field=models.ForeignKey(
                blank=True,
                help_text="Task pool whose items seed this project tasks (selected at creation).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="workspaces.taskpool",
            ),
        ),
    ]
