# Generated by Django 5.1.15 on 2026-07-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0041_alter_project_task_pool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("project_manager", "Project Manager"),
                    ("annotator", "Annotator"),
                    ("reviewer", "Reviewer"),
                    ("member", "Member"),
                ],
                db_index=True,
                default="annotator",
                help_text="Project-scope role: project_manager, annotator, or reviewer.",
                max_length=32,
                verbose_name="role",
            ),
        ),
    ]
