# Generated by Django 5.1.15 on 2026-06-17 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0002_workspacefileupload"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="workspacefileupload",
            new_name="workspace_f_workspa_9db2bd_idx",
            old_name="workspace_f_workspa_bf3bd0_idx",
        ),
    ]
