# Generated by Django 5.1.15 on 2026-06-18 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workspaces",
            "0003_rename_workspace_f_workspa_bf3bd0_idx_workspace_f_workspa_9db2bd_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(help_text="Task data for this item.")),
                (
                    "data_type",
                    models.CharField(
                        db_index=True,
                        default="file",
                        max_length=32,
                        verbose_name="data type",
                    ),
                ),
                (
                    "index",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Position within the source dataset.",
                        verbose_name="index",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        help_text="Dataset (workspace file upload) this item came from.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="workspaces.workspacefileupload",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace that owns the item (denormalized for queries).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dataset_items",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "dataset_item",
                "ordering": ["dataset_id", "index"],
            },
        ),
        migrations.CreateModel(
            name="WorkPool",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="title")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_pools_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace that owns the work pool.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_pools",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "work_pool",
            },
        ),
        migrations.CreateModel(
            name="WorkPoolItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "dataset_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pool_items",
                        to="workspaces.datasetitem",
                    ),
                ),
                (
                    "work_pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="workspaces.workpool",
                    ),
                ),
            ],
            options={
                "db_table": "work_pool_item",
            },
        ),
        migrations.AddIndex(
            model_name="datasetitem",
            index=models.Index(
                fields=["workspace", "data_type"], name="dataset_ite_workspa_84b8b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datasetitem",
            index=models.Index(
                fields=["dataset", "index"], name="dataset_ite_dataset_e7c367_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workpool",
            index=models.Index(
                fields=["workspace", "-created_at"], name="work_pool_workspa_49772d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workpool",
            constraint=models.UniqueConstraint(
                fields=("workspace", "title"), name="uniq_work_pool_title_per_workspace"
            ),
        ),
        migrations.AddIndex(
            model_name="workpoolitem",
            index=models.Index(
                fields=["work_pool"], name="work_pool_i_work_po_d7fb34_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workpoolitem",
            constraint=models.UniqueConstraint(
                fields=("work_pool", "dataset_item"), name="uniq_work_pool_item"
            ),
        ),
    ]
