# Generated by Django 5.1.15 on 2026-06-30 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0005_rename_task_pool_terms"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # (The constraint + index that reference the renamed FK fields were dropped in
        # migration 0005, before the rename; here we only update related_names and
        # re-create the index/constraint against the new field names.)
        migrations.AlterField(
            model_name="taskpool",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_pools_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="taskpool",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace that owns the task pool.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_pools",
                to="workspaces.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="tasksourceitem",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace that owns the item (denormalized for queries).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_source_items",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddIndex(
            model_name="taskpoolitem",
            index=models.Index(
                fields=["task_pool"], name="work_pool_i_task_po_63257a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="taskpoolitem",
            constraint=models.UniqueConstraint(
                fields=("task_pool", "task_source_item"), name="uniq_work_pool_item"
            ),
        ),
    ]
