# Generated by Django 5.1.15 on 2026-06-18 23:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0039_project_work_pool"),
        ("workspaces", "0004_datasetitem_workpool_workpoolitem_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("KRW", "Korean Won"),
                            ("JPY", "Japanese Yen"),
                        ],
                        help_text="Currency of the payment; must match the earnings currency it settles.",
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Amount paid in the given currency.",
                        max_digits=16,
                        verbose_name="amount",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="paid at"
                    ),
                ),
                ("memo", models.TextField(blank=True, default="", verbose_name="memo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Worker (member) the payment was made to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace the payment is recorded under.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_records",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "compensation_payment_record",
                "ordering": ("-paid_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ProjectCompensationPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("KRW", "Korean Won"),
                            ("JPY", "Japanese Yen"),
                        ],
                        default="USD",
                        help_text="Currency for this project's rates and earnings.",
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "annotation_unit_price",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Paid once per qualified (compensable) annotated data item.",
                        max_digits=14,
                        verbose_name="annotation unit price",
                    ),
                ),
                (
                    "review_unit_price",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Paid once per qualified (compensable) reviewed data item.",
                        max_digits=14,
                        verbose_name="review unit price",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        help_text="Project this pricing applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compensation_policy",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_compensation_policy",
            },
        ),
    ]
