# Generated by Django 5.1.15 on 2026-07-01 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compensation", "0001_initial"),
        ("projects", "0041_alter_project_task_pool"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrecord",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Project this payment settles (settlement unit). Null = legacy workspace-level payment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_records",
                to="projects.project",
            ),
        ),
    ]
