# Generated by Django 5.1.15 on 2026-06-17 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("io_storages", "0022_normalize_localfiles_paths"),
        (
            "workspaces",
            "0003_rename_workspace_f_workspa_bf3bd0_idx_workspace_f_workspa_9db2bd_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="S3WorkspaceImportStorage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last sync finished time",
                        null=True,
                        verbose_name="last sync",
                    ),
                ),
                (
                    "last_sync_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Count of tasks synced last time",
                        null=True,
                        verbose_name="last sync count",
                    ),
                ),
                (
                    "last_sync_job",
                    models.CharField(
                        blank=True,
                        help_text="Last sync job ID",
                        max_length=256,
                        null=True,
                        verbose_name="last_sync_job",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initialized", "Initialized"),
                            ("queued", "Queued"),
                            ("in_progress", "In progress"),
                            ("failed", "Failed"),
                            ("completed", "Completed"),
                            ("completed_with_errors", "Completed with errors"),
                        ],
                        default="initialized",
                        max_length=64,
                    ),
                ),
                (
                    "traceback",
                    models.TextField(
                        blank=True,
                        help_text="Traceback report for the last failed sync",
                        null=True,
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        default=dict,
                        help_text="Meta and debug information about storage processes",
                        null=True,
                        verbose_name="meta",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Cloud storage title",
                        max_length=256,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Cloud storage description",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creation time",
                        verbose_name="created at",
                    ),
                ),
                (
                    "synchronizable",
                    models.BooleanField(
                        default=True,
                        help_text="If storage can be synced",
                        verbose_name="synchronizable",
                    ),
                ),
                (
                    "bucket",
                    models.TextField(
                        blank=True,
                        help_text="S3 bucket name",
                        null=True,
                        verbose_name="bucket",
                    ),
                ),
                (
                    "prefix",
                    models.TextField(
                        blank=True,
                        help_text="S3 bucket prefix",
                        null=True,
                        verbose_name="prefix",
                    ),
                ),
                (
                    "regex_filter",
                    models.TextField(
                        blank=True,
                        help_text="Cloud storage regex for filtering objects",
                        null=True,
                        verbose_name="regex_filter",
                    ),
                ),
                (
                    "use_blob_urls",
                    models.BooleanField(
                        default=False,
                        help_text="Interpret objects as BLOBs and generate URLs",
                        verbose_name="use_blob_urls",
                    ),
                ),
                (
                    "aws_access_key_id",
                    models.TextField(
                        blank=True,
                        help_text="AWS_ACCESS_KEY_ID",
                        null=True,
                        verbose_name="aws_access_key_id",
                    ),
                ),
                (
                    "aws_secret_access_key",
                    models.TextField(
                        blank=True,
                        help_text="AWS_SECRET_ACCESS_KEY",
                        null=True,
                        verbose_name="aws_secret_access_key",
                    ),
                ),
                (
                    "aws_session_token",
                    models.TextField(
                        blank=True,
                        help_text="AWS_SESSION_TOKEN",
                        null=True,
                        verbose_name="aws_session_token",
                    ),
                ),
                (
                    "aws_sse_kms_key_id",
                    models.TextField(
                        blank=True,
                        help_text="AWS SSE KMS Key ID",
                        null=True,
                        verbose_name="aws_sse_kms_key_id",
                    ),
                ),
                (
                    "region_name",
                    models.TextField(
                        blank=True,
                        help_text="AWS Region",
                        null=True,
                        verbose_name="region_name",
                    ),
                ),
                (
                    "s3_endpoint",
                    models.TextField(
                        blank=True,
                        help_text="S3 Endpoint",
                        null=True,
                        verbose_name="s3_endpoint",
                    ),
                ),
                (
                    "presign",
                    models.BooleanField(
                        default=True,
                        help_text="Generate presigned URLs",
                        verbose_name="presign",
                    ),
                ),
                (
                    "presign_ttl",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Presigned URLs TTL (in minutes)",
                        verbose_name="presign_ttl",
                    ),
                ),
                (
                    "recursive_scan",
                    models.BooleanField(
                        default=False,
                        help_text="Perform recursive scan over the bucket content",
                        verbose_name="recursive scan",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace that owns this storage.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)ss",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="s3importstorage",
            name="parent_storage",
            field=models.ForeignKey(
                blank=True,
                help_text="Workspace-scope storage this project storage was derived from.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_storages",
                to="io_storages.s3workspaceimportstorage",
            ),
        ),
    ]
