# Generated by Django 5.1.15 on 2026-07-08 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("io_storages", "0024_azureblobworkspaceimportstorage_and_more"),
        (
            "workspaces",
            "0007_tasksourceitem_predictions_tasksourceitem_source_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="azureblobworkspaceimportstorage",
            name="task_pool",
            field=models.ForeignKey(
                blank=True,
                help_text="Task pool that synced items are added to automatically.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="azure_sources",
                to="workspaces.taskpool",
            ),
        ),
    ]
