# Generated by Django 5.1.15 on 2026-07-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="expires at"
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="revoked",
            field=models.BooleanField(default=False, verbose_name="revoked"),
        ),
    ]
