export const DEFAULT_HOTKEYS = [
  // Annotation Controls
  {
    id: 100,
    section: "annotation",
    element: "annotation:submit",
    label: "어노테이션 제출",
    key: "ctrl+enter",
    description: "현재 어노테이션을 제출합니다",
    active: true,
  },
  {
    id: 200,
    section: "annotation",
    element: "annotation:skip",
    label: "작업 건너뛰기",
    key: "ctrl+space",
    description: "현재 작업을 건너뜁니다",
    active: true,
  },
  {
    id: 300,
    section: "annotation",
    element: "annotation:undo",
    label: "실행 취소",
    key: "ctrl+z",
    description: "마지막 동작을 실행 취소합니다",
    active: true,
  },
  {
    id: 400,
    section: "annotation",
    element: "annotation:redo",
    label: "다시 실행",
    key: "ctrl+shift+z",
    description: "실행 취소한 동작을 다시 실행합니다",
    active: true,
  },

  // Data Manager
  {
    id: 500,
    section: "data_manager",
    element: "dm.focus-previous",
    label: "이전 작업으로 포커스",
    key: "shift+up",
    description: "이전 작업으로 포커스를 이동합니다",
    active: true,
  },
  {
    id: 600,
    section: "data_manager",
    element: "dm.focus-next",
    label: "다음 작업으로 포커스",
    key: "shift+down",
    description: "다음 작업으로 포커스를 이동합니다",
    active: true,
  },
  {
    id: 700,
    section: "data_manager",
    element: "dm.close-labeling",
    label: "닫힌 작업으로 포커스",
    key: "shift+left",
    description: "닫힌 작업 열로 포커스를 이동합니다",
    active: true,
  },
  {
    id: 800,
    section: "data_manager",
    element: "dm.open-labeling",
    label: "열린 작업으로 포커스",
    key: "shift+right",
    description: "열린 작업 열로 포커스를 이동합니다",
    active: true,
  },
  {
    id: 900,
    section: "data_manager",
    element: "dm.toggle-bulk-sidebar-minimization",
    label: "일괄 작업 사이드바 토글",
    key: "shift+.",
    description: "일괄 작업 사이드바를 최소화하거나 확장합니다",
    active: true,
  },

  // Region Management
  {
    id: 1100,
    section: "regions",
    element: "region:delete-all",
    label: "모든 영역 삭제",
    key: "ctrl+backspace",
    description: "모든 영역을 삭제합니다",
    active: true,
  },
  {
    id: 1200,
    section: "regions",
    element: "region:focus",
    label: "첫 영역으로 포커스",
    key: "enter",
    description: "포커스 가능한 첫 영역으로 포커스를 이동합니다",
    active: true,
  },
  {
    id: 1300,
    section: "regions",
    element: "region:relation",
    label: "영역 관계 생성",
    key: "alt+r",
    description: "선택한 영역 사이에 관계를 생성합니다",
    active: true,
  },
  {
    id: 1400,
    section: "regions",
    element: "region:visibility",
    label: "영역 표시 토글",
    key: "alt+h",
    description: "선택한 영역을 표시하거나 숨깁니다",
    active: true,
  },
  {
    id: 1500,
    section: "regions",
    element: "region:visibility-all",
    label: "모든 영역 표시 토글",
    key: "ctrl+h",
    description: "모든 영역을 표시하거나 숨깁니다",
    active: true,
  },
  {
    id: 1600,
    section: "regions",
    element: "region:lock",
    label: "영역 잠금",
    key: "alt+l",
    description: "선택한 영역을 잠그거나 잠금 해제합니다",
    active: true,
  },
  {
    id: 1700,
    section: "regions",
    element: "region:meta",
    label: "영역 메타데이터 편집",
    key: "alt+m",
    description: "선택한 영역의 메타데이터를 편집합니다",
    active: true,
  },
  {
    id: 1800,
    section: "regions",
    element: "region:unselect",
    label: "영역 선택 해제",
    key: "u",
    description: "현재 선택된 영역을 선택 해제합니다",
    active: true,
  },
  {
    id: 1900,
    section: "regions",
    element: "region:exit",
    label: "영역 모드 종료",
    key: "escape",
    description: "관계 모드를 종료하고 영역 선택을 해제합니다",
    active: true,
  },
  {
    id: 2000,
    section: "regions",
    element: "region:delete",
    label: "선택한 영역 삭제",
    key: "backspace",
    description: "현재 선택된 영역을 삭제합니다",
    active: true,
  },
  {
    id: 2100,
    section: "regions",
    element: "region:cycle",
    label: "영역 순환",
    key: "alt+.",
    description: "모든 영역을 순환합니다",
    active: true,
  },
  {
    id: 2200,
    section: "regions",
    element: "region:duplicate",
    label: "영역 복제",
    key: "ctrl+d",
    description: "선택한 영역의 복사본을 생성합니다",
    active: true,
  },
  {
    id: 2300,
    section: "regions",
    element: "segment:delete",
    label: "세그먼트 삭제",
    key: "delete",
    description: "선택한 세그먼트를 삭제합니다",
    active: true,
  },

  // Editor - Audio Controls
  {
    id: 2400,
    section: "audio",
    element: "audio:back",
    label: "1초 되감기",
    key: "ctrl+b",
    description: "오디오를 1초 되감습니다",
    active: true,
  },
  {
    id: 2500,
    section: "audio",
    element: "audio:playpause",
    label: "오디오 재생 / 일시정지",
    key: "ctrl+p",
    description: "오디오 재생을 토글합니다",
    active: true,
  },
  {
    id: 2600,
    section: "audio",
    element: "audio:step-backward",
    label: "뒤로 한 단계",
    key: "alt+a",
    description: "한 프레임 뒤로 이동합니다",
    active: true,
  },
  {
    id: 2700,
    section: "audio",
    element: "audio:step-forward",
    label: "앞으로 한 단계",
    key: "alt+d",
    description: "한 프레임 앞으로 이동합니다",
    active: true,
  },

  // Editor - Video Controls
  {
    id: 2800,
    section: "video",
    element: "media:playpause",
    label: "비디오 재생 / 일시정지",
    key: "ctrl+alt+space",
    description: "비디오 재생을 토글합니다",
    active: true,
  },
  {
    id: 2900,
    section: "video",
    element: "media:step-backward",
    label: "뒤로 한 단계",
    key: "alt+left",
    description: "한 프레임 뒤로 이동합니다",
    active: true,
  },
  {
    id: 3000,
    section: "video",
    element: "media:step-forward",
    label: "앞으로 한 단계",
    key: "alt+right",
    description: "한 프레임 앞으로 이동합니다",
    active: true,
  },
  {
    id: 3100,
    section: "video",
    element: "video:keyframe-backward",
    label: "이전 키프레임",
    key: "ctrl+alt+left",
    description: "이전 키프레임으로 이동합니다",
    active: true,
  },
  {
    id: 3200,
    section: "video",
    element: "video:keyframe-forward",
    label: "다음 키프레임",
    key: "ctrl+alt+right",
    description: "다음 키프레임으로 이동합니다",
    active: true,
  },
  {
    id: 3300,
    section: "video",
    element: "video:backward",
    label: "뒤로 탐색",
    key: "alt+left",
    description: "비디오를 뒤로 탐색합니다",
    active: true,
  },
  {
    id: 3400,
    section: "video",
    element: "video:rewind",
    label: "첫 프레임",
    key: "shift+ctrl+alt+left",
    description: "첫 프레임으로 이동합니다",
    active: true,
  },
  {
    id: 3500,
    section: "video",
    element: "video:forward",
    label: "앞으로 탐색",
    key: "shift+alt+right",
    description: "비디오를 앞으로 탐색합니다",
    active: true,
  },
  {
    id: 3600,
    section: "video",
    element: "video:fastforward",
    label: "마지막 프레임",
    key: "shift+ctrl+alt+right",
    description: "마지막 프레임으로 이동합니다",
    active: true,
  },
  {
    id: 3700,
    section: "video",
    element: "video:hop-backward",
    label: "뒤로 건너뛰기",
    key: "shift+alt+left",
    description: "빠르게 뒤로 건너뜁니다",
    active: true,
  },
  {
    id: 3800,
    section: "video",
    element: "video:hop-forward",
    label: "앞으로 건너뛰기",
    key: "shift+alt+right",
    description: "빠르게 앞으로 건너뜁니다",
    active: true,
  },

  // Editor - Time Series Controls
  {
    id: 3900,
    section: "timeseries",
    element: "ts:grow-left",
    label: "왼쪽으로 확장",
    key: "left",
    description: "영역을 왼쪽으로 확장합니다",
    active: true,
  },
  {
    id: 4000,
    section: "timeseries",
    element: "ts:grow-right",
    label: "오른쪽으로 확장",
    key: "right",
    description: "영역을 오른쪽으로 확장합니다",
    active: true,
  },
  {
    id: 4100,
    section: "timeseries",
    element: "ts:shrink-left",
    label: "왼쪽으로 축소",
    key: "alt+left",
    description: "영역을 왼쪽에서부터 축소합니다",
    active: true,
  },
  {
    id: 4200,
    section: "timeseries",
    element: "ts:shrink-right",
    label: "오른쪽으로 축소",
    key: "alt+right",
    description: "영역을 오른쪽에서부터 축소합니다",
    active: true,
  },
  {
    id: 4300,
    section: "timeseries",
    element: "ts:grow-left-large",
    label: "왼쪽으로 확장 (크게)",
    key: "shift+left",
    description: "영역을 왼쪽으로 크게 확장합니다",
    active: true,
  },
  {
    id: 4400,
    section: "timeseries",
    element: "ts:grow-right-large",
    label: "오른쪽으로 확장 (크게)",
    key: "shift+right",
    description: "영역을 오른쪽으로 크게 확장합니다",
    active: true,
  },
  {
    id: 4500,
    section: "timeseries",
    element: "ts:shrink-left-large",
    label: "왼쪽으로 축소 (크게)",
    key: "shift+alt+left",
    description: "영역을 왼쪽에서부터 크게 축소합니다",
    active: true,
  },
  {
    id: 4600,
    section: "timeseries",
    element: "ts:shrink-right-large",
    label: "오른쪽으로 축소 (크게)",
    key: "shift+alt+right",
    description: "영역을 오른쪽에서부터 크게 축소합니다",
    active: true,
  },

  // Image Gallery Controls
  {
    id: 4700,
    section: "image_gallery",
    element: "image:prev",
    label: "이전 이미지",
    key: "ctrl+left",
    description: "이전 이미지를 봅니다",
    active: true,
  },
  {
    id: 4800,
    section: "image_gallery",
    element: "image:next",
    label: "다음 이미지",
    key: "ctrl+right",
    description: "다음 이미지를 봅니다",
    active: true,
  },

  {
    id: 5000,
    section: "tools",
    element: "tool:zoom-in",
    label: "확대",
    key: "ctrl+plus",
    description: "이미지를 확대합니다",
    active: true,
  },
  {
    id: 5100,
    section: "tools",
    element: "tool:pan-image",
    label: "이미지 이동",
    key: "H",
    description: "이미지를 이리저리 이동합니다",
    active: true,
  },
  {
    id: 5200,
    section: "tools",
    element: "tool:zoom-to-fit",
    label: "화면에 맞추기",
    key: "shift+1",
    description: "전체 이미지가 화면에 맞도록 확대/축소합니다",
    active: true,
  },
  {
    id: 5300,
    section: "tools",
    element: "tool:zoom-to-actual",
    label: "100%로 보기",
    key: "shift+2",
    description: "이미지를 실제 크기(100%)로 봅니다",
    active: true,
  },
  {
    id: 5400,
    section: "tools",
    element: "tool:zoom-out",
    label: "축소",
    key: "ctrl+minus",
    description: "이미지를 축소합니다",
    active: true,
  },
  {
    id: 5401,
    section: "tools",
    element: "tool:move",
    label: "이동 도구",
    key: "V",
    description: "어노테이션 위치를 조정하는 이동 도구를 선택합니다",
    active: true,
  },
  {
    id: 5402,
    section: "tools",
    element: "tool:brush",
    label: "브러시 도구",
    key: "B",
    description: "브러시 도구를 선택합니다",
    active: true,
  },

  {
    id: 5500,
    section: "tools",
    element: "tool:ellipse",
    label: "타원 도구",
    key: "O",
    description: "타원 도구를 선택합니다",
    active: true,
  },
  {
    id: 5600,
    section: "tools",
    element: "tool:eraser",
    label: "지우개 도구",
    key: "E",
    description: "지우개 도구를 선택합니다",
    active: true,
  },
  {
    id: 5700,
    section: "tools",
    element: "tool:auto-detect",
    label: "자동 감지",
    key: "M",
    description: "자동 감지 도구를 사용해 영역을 자동으로 제안합니다",
    active: true,
  },
  {
    id: 5900,
    section: "tools",
    element: "tool:key-point",
    label: "키포인트 도구",
    key: "K",
    description: "키포인트 어노테이션 도구를 선택합니다",
    active: true,
  },
  {
    id: 6000,
    section: "tools",
    element: "tool:magic-wand",
    label: "마술봉 도구",
    key: "W",
    description: "스마트 영역 선택을 위한 마술봉 도구를 선택합니다",
    active: true,
  },
  {
    id: 6100,
    section: "tools",
    element: "tool:polygon",
    label: "다각형 도구",
    key: "P",
    description: "다각형 어노테이션 도구를 선택합니다",
    active: true,
  },
  {
    id: 6200,
    section: "tools",
    element: "tool:rect",
    label: "사각형 도구",
    key: "R",
    description: "사각형 어노테이션 도구를 선택합니다",
    active: true,
  },
  {
    id: 6201,
    section: "tools",
    element: "tool:rect-3point",
    label: "3점 사각형",
    key: "shift+R",
    description: "3점 선택으로 회전된 사각형을 그립니다",
    active: true,
  },

  {
    id: 6300,
    section: "tools",
    element: "tool:rotate-left",
    label: "왼쪽으로 회전",
    key: "alt+left",
    description: "이미지를 왼쪽으로 90° 회전합니다",
    active: true,
  },
  {
    id: 6400,
    section: "tools",
    element: "tool:rotate-right",
    label: "오른쪽으로 회전",
    key: "alt+right",
    description: "이미지를 오른쪽으로 90° 회전합니다",
    active: true,
  },
  {
    id: 6700,
    section: "tools",
    element: "tool:decrease-tool",
    label: "도구 크기 줄이기",
    key: "[",
    description: "도구 크기를 줄입니다",
    active: true,
  },
  {
    id: 6800,
    section: "tools",
    element: "tool:increase-tool",
    label: "도구 크기 늘리기",
    key: "]",
    description: "도구 크기를 늘립니다",
    active: true,
  },

  // Paragraph Navigation
  {
    id: 6900,
    section: "paragraphs",
    element: "phrases:next-phrase",
    label: "다음 구절",
    key: "ctrl+down",
    description: "문단 보기에서 다음 구절로 이동합니다",
    active: true,
  },
  {
    id: 7000,
    section: "paragraphs",
    element: "phrases:previous-phrase",
    label: "이전 구절",
    key: "ctrl+up",
    description: "문단 보기에서 이전 구절로 이동합니다",
    active: true,
  },
  {
    id: 7100,
    section: "paragraphs",
    element: "phrases:select_all_annotate",
    label: "모두 선택 후 어노테이션",
    key: "ctrl+shift+a",
    description: "현재 구절의 모든 텍스트를 선택하고 어노테이션을 생성합니다",
    active: true,
  },
  {
    id: 7200,
    section: "paragraphs",
    element: "phrases:next-region",
    label: "구절 내 다음 영역",
    key: "ctrl+right",
    description: "현재 구절 내에서 다음 영역으로 이동합니다",
    active: true,
  },
  {
    id: 7300,
    section: "paragraphs",
    element: "phrases:previous-region",
    label: "구절 내 이전 영역",
    key: "ctrl+left",
    description: "현재 구절 내에서 이전 영역으로 이동합니다",
    active: true,
  },
];

export const HOTKEY_SECTIONS = [
  {
    id: "annotation",
    title: "어노테이션 작업",
    description: "제출, 건너뛰기, 실행 취소 및 다시 실행 등 일반적인 어노테이션 작업 단축키",
  },

  {
    id: "data_manager",
    title: "데이터 관리자",
    description: "프로젝트 데이터 관리자에서 작업을 탐색하고 관리하는 단축키",
  },

  {
    id: "regions",
    title: "영역 관리",
    description: "어노테이션 영역을 생성, 선택 및 조작하는 단축키",
  },

  {
    id: "tools",
    title: "도구",
    description: "이미지 라벨링 시 도구 패널을 제어하는 단축키",
  },

  {
    id: "audio",
    title: "오디오 조작",
    description: "오디오 재생 및 탐색을 제어하는 단축키",
  },
  {
    id: "video",
    title: "비디오 조작",
    description: "비디오 재생 및 탐색을 제어하는 단축키",
  },
  {
    id: "timeseries",
    title: "시계열 조작",
    description: "시계열 데이터 영역을 조작하는 단축키",
  },
  {
    id: "image_gallery",
    title: "이미지 갤러리 탐색",
    description: "다중 이미지 작업에서 이미지 간을 탐색하는 단축키",
  },
  {
    id: "paragraphs",
    title: "문단 탐색",
    description: "문단/대화 보기에서 구절과 영역을 탐색하는 단축키",
  },
];

/**
 * URL patterns mapped to their corresponding hotkey sections
 * Used to automatically determine which shortcuts to display based on current page
 */
export const URL_TO_SECTION_MAPPING = [
  {
    regex: /\/projects\/\d+\/data\/?\?.*task=\d+/i,
    section: ["annotation", "regions"],
  },
  {
    regex: /\/projects\/\d+\/data\/?$/i,
    section: "data_manager",
  },
];
